disabled_rules:
  - control_statement
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - line_length
  - nesting
  - todo
  - trailing_whitespace
  - type_body_length
  - type_name
  - unused_optional_binding
  - variable_name
  - weak_delegate

opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

force_unwrapping:
  severity: error
  
implicitly_unwrapped_optional:
  severity: error

trailing_comma:
  mandatory_comma: true

excluded:
  - Pods
  - ___PACKAGENAME___/CoreDataAndModels/private
  - ___PACKAGENAME___/Scripts
  - ___PACKAGENAME___/Resources
  - R.generated.swift
  - vendor # If running on Travis CI, a "vendor" directory will be added that may have Swift files that should not be linted.
